linters:
  enable:
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gofmt
    - goimports
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning

  misspell:
    locale: US

issues:
  exclude-dirs:
    - vendor
    - dist
    - .cache

  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
    - linters:
        - govet
      text: "fieldalignment"
    - linters:
        - govet
      text: "shadow"
    - text: "comandos"
      linters:
        - misspell